### ISSUE TITLE
Instalar no Debian 8

### ISSUE THREAD

**Issue by cadilhe** [iotaorg/Iota-RNSP#10]
Para instalar o IOTA no Debian 8 basta seguir os mesmos procedimentos?
Obrigado

**Comment by renatocron** [comment]
Olá Carlos,

Provavelmente é possível instalar sem muitos problemas, só não rodar as partes que modificam o /etc/apt/sources.list

Pode usar o próprio postgresql que vem no respotorio do debian 8, que é a versão 9.4

O perl também não precisa ser o perl-5.16.3, rodo já com o v5.20.3
